//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaCloudProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckRefBrands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TruckRefBrands()
        {
            this.TruckDetail = new HashSet<TruckDetail>();
        }
    
        public int CarRefBrandID { get; set; }
        public string CarRefBrandName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckDetail> TruckDetail { get; set; }
    }
}
